version: '1.1.{build}'

configuration:
  - Release
  - Debug

platform:
  - Any CPU
#  - x86
#  - x64

assembly_info:
  patch: true
  file: Properties\SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

# Restore nuget packages before running the build
before_build:
  - nuget restore

build:
  verbosity: minimal
  parallel: true
  project: WinDbgCs.sln
